%% Train mDOF Recognition Network
% Former Author: JoeyBG;
% Improved By: JoeyBG;
% Affiliation: Beijing Institute of Technology, Radar Research Lab;
% Date: 2026-06-02;
% Language & Platform: MATLAB R2025b.
%
% Introduction:
% This function trains the two-branch mDOF recognition network with MATLAB
% Deep Learning Toolbox and displays the real-time training-progress window.

%% Function Body
function [Net, Train_Info, Layer_Graph] = TrainmDOFNetwork(Training_Datastore, Validation_Datastore, Config, Number_of_Classes)

    Layer_Graph = BuildDualBranchmDOFNetwork(Config, Number_of_Classes);

    if Config.Training.ShowTrainingProgress
        Plot_Mode = "training-progress";
    else
        Plot_Mode = "none";
    end

    Base_Options = { ...
        'ExecutionEnvironment',Config.Training.ExecutionEnvironment, ...
        'InitialLearnRate',Config.Training.InitialLearnRate, ...
        'LearnRateSchedule','piecewise', ...
        'LearnRateDropFactor',Config.Training.LearnRateDropFactor, ...
        'LearnRateDropPeriod',Config.Training.LearnRateDropPeriod, ...
        'MaxEpochs',Config.Training.MaxEpochs, ...
        'MiniBatchSize',Config.Training.MiniBatchSize, ...
        'Shuffle','every-epoch', ...
        'L2Regularization',Config.Training.L2Regularization, ...
        'GradientThreshold',1, ...
        'Plots',Plot_Mode, ...
        'Verbose',true};

    if ~isempty(Validation_Datastore)
        Options = trainingOptions('adam',Base_Options{:}, ...
            'ValidationData',Validation_Datastore, ...
            'ValidationFrequency',Config.Training.ValidationFrequency, ...
            'ValidationPatience',Config.Training.ValidationPatience, ...
            'OutputNetwork',Config.Training.OutputNetwork);
    else
        Options = trainingOptions('adam',Base_Options{:}, ...
            'OutputNetwork','last-iteration');
    end

    [Net, Train_Info] = trainNetwork(Training_Datastore,Layer_Graph,Options);

end
